-- FunEvent 初始 schema（PostgreSQL 17）
--
-- 這份檔案不是手寫的：先讓 Hibernate 的 ddl-auto=update 在空的 PostgreSQL 上
-- 把 14 張表建出來，再用 pg_dump --schema-only 匯出，然後只做三件事：
--   1. 清掉 psql 的 meta-command（\restrict）與 SET 前綴 —— Flyway 走 JDBC，
--      那些不是 SQL，會直接炸
--   2. identity 欄位從 pg_dump 的「先建表再 ALTER TABLE ... ADD GENERATED」
--      改寫成 CREATE TABLE 裡的一行（PostgreSQL 產生的序列名一樣是 <table>_id_seq）
--   3. Hibernate 自動產生的雜湊約束名改成看得懂的名字
--
-- ⚠️ 從這個檔案開始，schema 由 Flyway 管，ddl-auto 是 validate。
--    改 entity 加欄位不會再自動生效 —— 要寫一個新的 V2__xxx.sql。
-- ⚠️ 已經套用過的 migration 檔不能再改內容，Flyway 會用 checksum 擋下來。


-- ══ 表 ═══════════════════════════════════════════════════════════════════

create table users (
    id            bigint generated by default as identity not null,
    created_at    timestamp(6) with time zone not null,
    email         varchar(255) not null,
    name          varchar(255),
    -- OAuth 註冊的帳號沒有密碼，所以可以是 null
    password_hash varchar(255),
    role          varchar(20) not null,
    updated_at    timestamp(6) with time zone not null,
    constraint users_role_check check (role in ('ADMIN', 'USER'))
);

create table organizers (
    id           bigint generated by default as identity not null,
    created_at   timestamp(6) with time zone not null,
    introduction text,
    name         varchar(255) not null,
    updated_at   timestamp(6) with time zone not null,
    user_id      bigint not null
);

create table events (
    id            bigint generated by default as identity not null,
    address       varchar(255),
    category      varchar(30) not null,
    city          varchar(30) not null,
    created_at    timestamp(6) with time zone not null,
    description   text not null,
    district      varchar(50),
    end_at        timestamp(6) with time zone not null,
    location_name varchar(255),
    name          varchar(255) not null,
    start_at      timestamp(6) with time zone not null,
    status        varchar(20) not null,
    updated_at    timestamp(6) with time zone not null,
    organizer_id  bigint not null,
    constraint ck_events_end_after_start check (end_at > start_at),
    constraint events_category_check check (category in (
        'NATURE_SCIENCE', 'LANGUAGE', 'ART_CULTURE', 'SPORT',
        'LIFE_EXPERIENCE', 'DIGITAL_SCIENCE', 'CREATIVE_DIY', 'MUSIC_GROOVE')),
    constraint events_city_check check (city in (
        'KEELUNG', 'TAIPEI', 'NEW_TAIPEI', 'TAOYUAN', 'HSINCHU_CITY', 'HSINCHU_COUNTY',
        'MIAOLI', 'TAICHUNG', 'CHANGHUA', 'NANTOU', 'YUNLIN', 'CHIAYI_CITY',
        'CHIAYI_COUNTY', 'TAINAN', 'KAOHSIUNG', 'PINGTUNG', 'YILAN', 'HUALIEN',
        'TAITUNG', 'PENGHU', 'KINMEN', 'LIENCHIANG')),
    constraint events_status_check check (status in ('DRAFT', 'PUBLISHED', 'CANCELLED'))
);

create table event_images (
    id         bigint generated by default as identity not null,
    created_at timestamp(6) with time zone not null,
    image_url  varchar(255) not null,
    sort_order integer not null,
    updated_at timestamp(6) with time zone not null,
    event_id   bigint not null
);

create table ticket_types (
    id            bigint generated by default as identity not null,
    capacity      integer not null,
    created_at    timestamp(6) with time zone not null,
    description   text,
    name          varchar(255) not null,
    price         numeric(10, 2) not null,
    sale_end_at   timestamp(6) with time zone,
    sale_start_at timestamp(6) with time zone,
    stock         integer not null,
    updated_at    timestamp(6) with time zone not null,
    event_id      bigint not null,
    constraint ck_ticket_types_price_non_negative check (price >= 0),
    constraint ck_ticket_types_sale_end_after_sale_start
        check (sale_start_at is null or sale_end_at is null or sale_end_at > sale_start_at),
    constraint ck_ticket_types_stock_non_negative check (stock >= 0),
    -- ⚠️ 這條是冪等壞掉時的警報器：restoreStock 刻意不加防呆條件，
    -- 重複回補庫存會直接撞這條約束炸開，而不是默默把數字加過頭
    constraint ck_ticket_types_stock_within_capacity check (stock <= capacity)
);

create table orders (
    id           bigint generated by default as identity not null,
    created_at   timestamp(6) with time zone not null,
    expires_at   timestamp(6) with time zone not null,
    paid_at      timestamp(6) with time zone,
    status       varchar(20) not null,
    total_amount numeric(10, 2) not null,
    updated_at   timestamp(6) with time zone not null,
    user_id      bigint not null,
    constraint orders_status_check check (status in ('PENDING', 'PAID', 'CANCELLED', 'REFUNDED'))
);

create table order_items (
    id               bigint generated by default as identity not null,
    created_at       timestamp(6) with time zone not null,
    quantity         integer not null,
    -- 下單當下的票種名稱與單價快照：票種之後改名或改價，歷史訂單不該跟著變
    ticket_type_name varchar(255) not null,
    unit_price       numeric(10, 2) not null,
    updated_at       timestamp(6) with time zone not null,
    order_id         bigint not null,
    ticket_type_id   bigint not null,
    constraint ck_order_items_quantity_positive check (quantity > 0),
    constraint ck_order_items_unit_price_non_negative check (unit_price >= 0)
);

create table payments (
    id                bigint generated by default as identity not null,
    amount            numeric(10, 2) not null,
    created_at        timestamp(6) with time zone not null,
    gateway_trade_no  varchar(255),
    merchant_trade_no varchar(20) not null,
    paid_at           timestamp(6) with time zone,
    raw_callback      text,
    status            varchar(20) not null,
    updated_at        timestamp(6) with time zone not null,
    order_id          bigint not null,
    constraint ck_payments_amount_non_negative check (amount >= 0),
    constraint payments_status_check check (status in ('PENDING', 'SUCCESS', 'FAILED'))
);

create table tickets (
    id            bigint generated by default as identity not null,
    created_at    timestamp(6) with time zone not null,
    status        varchar(20) not null,
    used_at       timestamp(6) with time zone,
    -- 核銷者。⚠️ Ticket 刻意沒有 token 欄位 —— QR 走 HMAC 簽章（{ticketId}.{HMAC}），
    -- 因為 QR 每次打開都要重畫，只存雜湊就再也算不回原文
    checked_in_by bigint,
    order_item_id bigint not null,
    constraint tickets_status_check check (status in ('VALID', 'USED', 'VOID'))
);

create table comments (
    id         bigint generated by default as identity not null,
    content    text,
    created_at timestamp(6) with time zone not null,
    rating     integer not null,
    event_id   bigint not null,
    user_id    bigint not null,
    constraint comments_rating_check check (rating >= 1 and rating <= 5)
);

create table favorites (
    id         bigint generated by default as identity not null,
    created_at timestamp(6) with time zone not null,
    event_id   bigint not null,
    user_id    bigint not null
);

create table refresh_tokens (
    id         bigint generated by default as identity not null,
    created_at timestamp(6) with time zone not null,
    expires_at timestamp(6) with time zone not null,
    -- 同一條輪替鏈共用一個 family_id，竊用偵測靠它一次撤銷整條
    family_id  uuid not null,
    revoked    boolean not null,
    token_hash varchar(255) not null,
    used       boolean not null,
    used_at    timestamp(6) with time zone,
    user_id    bigint not null
);

create table password_reset_tokens (
    id         bigint generated by default as identity not null,
    created_at timestamp(6) with time zone not null,
    expires_at timestamp(6) with time zone not null,
    token_hash varchar(255) not null,
    used       boolean not null,
    user_id    bigint not null
);

create table user_oauth_accounts (
    id           bigint generated by default as identity not null,
    created_at   timestamp(6) with time zone not null,
    provider     varchar(20) not null,
    provider_uid varchar(255) not null,
    user_id      bigint not null,
    constraint user_oauth_accounts_provider_check check (provider = 'GOOGLE')
);


-- ══ 主鍵 ═════════════════════════════════════════════════════════════════

alter table users                 add constraint users_pkey                 primary key (id);
alter table organizers            add constraint organizers_pkey            primary key (id);
alter table events                add constraint events_pkey                primary key (id);
alter table event_images          add constraint event_images_pkey          primary key (id);
alter table ticket_types          add constraint ticket_types_pkey          primary key (id);
alter table orders                add constraint orders_pkey                primary key (id);
alter table order_items           add constraint order_items_pkey           primary key (id);
alter table payments              add constraint payments_pkey              primary key (id);
alter table tickets               add constraint tickets_pkey               primary key (id);
alter table comments              add constraint comments_pkey              primary key (id);
alter table favorites             add constraint favorites_pkey             primary key (id);
alter table refresh_tokens        add constraint refresh_tokens_pkey        primary key (id);
alter table password_reset_tokens add constraint password_reset_tokens_pkey primary key (id);
alter table user_oauth_accounts   add constraint user_oauth_accounts_pkey   primary key (id);


-- ══ 唯一約束 ═════════════════════════════════════════════════════════════
--
-- ⚠️ 這些不只是「資料整潔」——它們是併發下的最後裁決者。
-- 重複評論、OAuth 首次登入撞號、綠界回呼重送，全部靠資料庫這一層擋，
-- 而不是「先查再寫」。多實例部署也因此不需要分散式鎖。

alter table users add constraint uk_users_email unique (email);

alter table organizers add constraint uk_organizers_user unique (user_id);

alter table payments add constraint uk_payments_merchant_trade_no unique (merchant_trade_no);

alter table comments add constraint uk_comments_event_user unique (event_id, user_id);

alter table favorites add constraint uk_favorites_user_event unique (event_id, user_id);

alter table refresh_tokens add constraint uk_refresh_tokens_token_hash unique (token_hash);

alter table password_reset_tokens
    add constraint uk_password_reset_tokens_token_hash unique (token_hash);

alter table user_oauth_accounts
    add constraint uk_user_oauth_accounts_provider_uid unique (provider, provider_uid);

alter table user_oauth_accounts
    add constraint uk_user_oauth_accounts_user_provider unique (user_id, provider);


-- ══ 索引 ═════════════════════════════════════════════════════════════════

create index idx_comments_event_created   on comments (event_id, created_at);
create index idx_favorites_user_created   on favorites (user_id, created_at);
-- 逾時取消的排程每分鐘掃一次，靠這條避免全表掃描
create index idx_orders_status_expires_at on orders (status, expires_at);
create index idx_refresh_tokens_family_id on refresh_tokens (family_id);
create index idx_tickets_order_item       on tickets (order_item_id);


-- ══ 外鍵 ═════════════════════════════════════════════════════════════════

alter table organizers
    add constraint fk_organizers_user foreign key (user_id) references users (id);

alter table events
    add constraint fk_events_organizer foreign key (organizer_id) references organizers (id);

alter table event_images
    add constraint fk_event_images_event foreign key (event_id) references events (id);

alter table ticket_types
    add constraint fk_ticket_types_event foreign key (event_id) references events (id);

alter table orders
    add constraint fk_orders_user foreign key (user_id) references users (id);

alter table order_items
    add constraint fk_order_items_order foreign key (order_id) references orders (id);

alter table order_items
    add constraint fk_order_items_ticket_type foreign key (ticket_type_id) references ticket_types (id);

alter table payments
    add constraint fk_payments_order foreign key (order_id) references orders (id);

alter table tickets
    add constraint fk_tickets_order_item foreign key (order_item_id) references order_items (id);

alter table tickets
    add constraint fk_tickets_checked_in_by foreign key (checked_in_by) references users (id);

alter table comments
    add constraint fk_comments_event foreign key (event_id) references events (id);

alter table comments
    add constraint fk_comments_user foreign key (user_id) references users (id);

alter table favorites
    add constraint fk_favorites_event foreign key (event_id) references events (id);

alter table favorites
    add constraint fk_favorites_user foreign key (user_id) references users (id);

alter table refresh_tokens
    add constraint fk_refresh_tokens_user foreign key (user_id) references users (id);

alter table password_reset_tokens
    add constraint fk_password_reset_tokens_user foreign key (user_id) references users (id);

alter table user_oauth_accounts
    add constraint fk_user_oauth_accounts_user foreign key (user_id) references users (id);
